### ISSUE TITLE
Connection is closed, but pool.allocated is not reduced

### ISSUE THREAD

**Issue by inovakov** [apigee/trireme-jdbc#4]
I noticed, that the "allocated" number of connections only grows and never decreases. As a result, after some time, when the "allocated" reaches "max", no new connections are created. And in the meantime, due to the idleTimeout connections are being closed. But the "allocated" number is not decreased. So, no new connections are created and there are no connections (or just one) to process requests.

**Comment by gbrail** [comment]
Good catch and that looks correct to me.

Do you want to try and attempt a patch and an updated test? It doesn't look
like a big change but we should beef up the test suite so that we get it
right this time.

On Wed, Nov 25, 2015 at 10:15 AM, Ivan Novakov <notifications@github.com>
wrote:

> I noticed, that the "allocated" number of connections only grows and never
> decreases. As a result, after some time, when the "allocated" reaches
> "max", no new connections are created. And in the meantime, due to the
> idleTimeout connections are being closed. But the "allocated" number is not
> decreased. So, no new connections are created and there are no connections
> (or just one) to process requests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee/trireme-jdbc/issues/4>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>
